version: "3.8"
services:
  server:
    image: ghcr.io/kingmojang/server:develop
    container_name: server
    restart: always
    ports:
      - "8080:8080"
    environment:
      USE_PROFILE: dev
    depends_on:
      - database
  database:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kingmojang
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]